name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}
        
        
    - name: Upload .env File
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "${{ github.ref == 'refs/heads/main' && secrets.ENV_FILE || secrets.ENV_FILE_DEV }}" > ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}/.env
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}
          echo "Installing dependencies with yarn..."
          npm install --legacy-peer-deps
           # Check if the app is already registered in PM2
          APP_NAME="${{ github.ref == 'refs/heads/main' && 'prod-vriddhe' || 'dev-vriddhe' }}"
          PORT="${{ github.ref == 'refs/heads/main' && '3301' || '3401' }}"
            echo "PM2 app '$APP_NAME' exists. Restarting..."
            pm2 delete "$APP_NAME"
            echo "Starting '$APP_NAME' from correct path..."
            pm2 start npm --name "$APP_NAME" -- run dev -- --port "$PORT"

          pm2 save
